const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94789123880"
const SESSION_ID = "PRABATH-MD~YrtXXJoZ#ecsLvv6Z_AbR_kiaP0J8tDFzvOGUsMltv-b2gji5Lzw"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
